version: "3"

services:

  frontend:
    build:
      context: ../
      dockerfile: ./cicd/Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    command: npm run start
