import '../../public/scss/style.scss'

import type { Metadata } from 'next'

import Footer from '@/app/components/Footer'
import Header from '@/app/components/Header'
import Head from '@/app/components/Head'
import OffCanvas from '@/app/components/OffCanvas'
import Calculator from '@/app/components/Calculator'
import ScrollToTop from '@/app/components/ScrollToTop'
import ImportCustomJS from '@/app/components/ImportCustomJS'
import CallToAction from '@/app/components/CallToAction'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru" className="h-100">
      <Head />
      <body className="d-flex flex-column h-100">
        <Header />
        <OffCanvas />

        {children}

        {/* <CallToAction /> */}

        <Footer />
        {/* <Calculator /> */}
        <ScrollToTop />

        <ImportCustomJS />
      </body>
    </html>
  )
}
