import '../../public/scss/style.scss'

import type { Metadata } from 'next'

import Footer from './components/Footer'
import Header from './components/Header'
import Head from './components/Head'
import OffCanvas from './components/OffCanvas'
import Calculator from './components/Calculator'
import ScrollToTop from './components/ScrollToTop'
import ImportCustomJS from './components/ImportCustomJS'
import CallToAction from './components/CallToAction'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru" className="h-100">
      <Head />
      <body className="d-flex flex-column h-100">
        <Header />
        <OffCanvas />

        {children}

        {/* <CallToAction /> */}

        <Footer />
        {/* <Calculator /> */}
        <ScrollToTop />

        <ImportCustomJS />
      </body>
    </html>
  )
}
